# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
standalone_tags:
  [
  ]
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
# tag_bundles:
#   [
#     {
#       name: 'CUSTOM_BUNDLE_NAME',
#       layout:
#         [
#           {id: ID, size: SIZE, x: X_POS, y: Y_POS, z: Z_POS, qw: QUAT_W_VAL, qx: QUAT_X_VAL, qy: QUAT_Y_VAL, qz: QUAT_Z_VAL},
#           ...
#         ]
#     },
#     ...
#   ]
tag_bundles:
  [
    {
      name: 'GATEN',
      layout:
        [
          {id: 4, size: 0.2286, x: -1.685, y: 0.501, z: -0.582},
          {id: 5, size: 0.2286, x: -0.264, y: 2.556, z: -0.575},
          {id: 6, size: 0.2286, x: 1.674, y: 0.985, z: -0.583}
        ]
    },
    {
      name: 'GATE2',
      layout:
        [
          {id: 24, size: 0.2286, x: -1.454, y: 0.607, z: -0.627},
          {id: 25, size: 0.2286, x: -0.253, y: 2.537, z: -0.622},
          {id: 26, size: 0.2286, x: 1.431, y: 1.114, z: -0.621}
        ]
    },
  ]
