%YAML:1.0

# Camera calibration and distortion parameters (OpenCV)
#Camera.fx: 615.6707153320312
#Camera.fy: 615.962158203125
#Camera.cx: 328.0010681152344
#Camera.cy: 241.31031799316406

Camera.fx: 618.2425537109375
Camera.fy: 618.5384521484375
Camera.cx: 327.95947265625
Camera.cy: 247.670654296875

# Camera distortion parameters (OpenCV)
Camera.k1: 0.0
Camera.k2: 0.0
Camera.p1: 0.0
Camera.p2: 0.0
Camera.k3: 0.0

Camera.width: 640
Camera.height: 480

# IR projector baseline times fx (aprox.)
#Camera.bf: 49.833290
Camera.bf: 49

# Camera frames per second
Camera.fps: 15.0

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Close/Far threshold. Baseline times.
ThDepth: 40.0

# Deptmap values factor (what pixel value in the depth image corresponds to 1m?)
DepthMapFactor: 720.0

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 2000

# ORB Extractor: Scale factor between levels in the scale pyramid
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast
ORBextractor.iniThFAST: 7
ORBextractor.minThFAST: 3
